// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FilterConfig holds filter strategy configuration
 */
export interface FilterConfig {
    "hashes": boolean;
    "dexpub": boolean;
    "mixins": boolean;
    "modrinth": boolean;
    "mcmod": boolean;
}

/**
 * IConfig is the main configuration structure
 */
export interface IConfig {
    "mirror": MirrorConfig;
    "filter": FilterConfig;
    "oaf": boolean;
    "autoZip": boolean;
    "showSponsorAd": boolean;
    "port"?: number;
    "host"?: string;
    "javaPath"?: string;
}

/**
 * MirrorConfig holds mirror configuration
 */
export interface MirrorConfig {
    "bmclapi": boolean;

    /**
     * "on" | "off" | "partial"
     */
    "mcimirror": string;
}
