// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FilterConfig holds filter strategy configuration
 */
export class FilterConfig {
    "hashes": boolean;
    "dexpub": boolean;
    "mixins": boolean;
    "modrinth": boolean;
    "mcmod": boolean;

    /** Creates a new FilterConfig instance. */
    constructor($$source: Partial<FilterConfig> = {}) {
        if (!("hashes" in $$source)) {
            this["hashes"] = false;
        }
        if (!("dexpub" in $$source)) {
            this["dexpub"] = false;
        }
        if (!("mixins" in $$source)) {
            this["mixins"] = false;
        }
        if (!("modrinth" in $$source)) {
            this["modrinth"] = false;
        }
        if (!("mcmod" in $$source)) {
            this["mcmod"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilterConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): FilterConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilterConfig($$parsedSource as Partial<FilterConfig>);
    }
}

/**
 * IConfig is the main configuration structure
 */
export class IConfig {
    "mirror": MirrorConfig;
    "filter": FilterConfig;
    "oaf": boolean;
    "autoZip": boolean;
    "showSponsorAd": boolean;
    "port"?: number;
    "host"?: string;
    "javaPath"?: string;

    /** Creates a new IConfig instance. */
    constructor($$source: Partial<IConfig> = {}) {
        if (!("mirror" in $$source)) {
            this["mirror"] = (new MirrorConfig());
        }
        if (!("filter" in $$source)) {
            this["filter"] = (new FilterConfig());
        }
        if (!("oaf" in $$source)) {
            this["oaf"] = false;
        }
        if (!("autoZip" in $$source)) {
            this["autoZip"] = false;
        }
        if (!("showSponsorAd" in $$source)) {
            this["showSponsorAd"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): IConfig {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mirror" in $$parsedSource) {
            $$parsedSource["mirror"] = $$createField0_0($$parsedSource["mirror"]);
        }
        if ("filter" in $$parsedSource) {
            $$parsedSource["filter"] = $$createField1_0($$parsedSource["filter"]);
        }
        return new IConfig($$parsedSource as Partial<IConfig>);
    }
}

/**
 * MirrorConfig holds mirror configuration
 */
export class MirrorConfig {
    "bmclapi": boolean;

    /**
     * "on" | "off" | "partial"
     */
    "mcimirror": string;

    /** Creates a new MirrorConfig instance. */
    constructor($$source: Partial<MirrorConfig> = {}) {
        if (!("bmclapi" in $$source)) {
            this["bmclapi"] = false;
        }
        if (!("mcimirror" in $$source)) {
            this["mcimirror"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MirrorConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): MirrorConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MirrorConfig($$parsedSource as Partial<MirrorConfig>);
    }
}

// Private type creation functions
const $$createType0 = MirrorConfig.createFrom;
const $$createType1 = FilterConfig.createFrom;
