// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService handles config operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * GetConfig returns the current configuration
 */
export function GetConfig(): $CancellablePromise<config$0.IConfig | null> {
    return $Call.ByID(4003623270).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveConfig saves the configuration
 */
export function SaveConfig(cfg: config$0.IConfig | null): $CancellablePromise<void> {
    return $Call.ByID(1561391947, cfg);
}

// Private type creation functions
const $$createType0 = config$0.IConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
