// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DexService is the main service for processing modpacks
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * StartTask starts processing a modpack from file data
 */
export function StartTask(fileData: string | null, filename: string, mode: string, template: string): $CancellablePromise<void> {
    return $Call.ByID(1446233042, fileData, filename, mode, template);
}

/**
 * StartTaskFromPath starts processing a modpack from a file path
 */
export function StartTaskFromPath(filePath: string, mode: string, template: string): $CancellablePromise<void> {
    return $Call.ByID(3419369309, filePath, mode, template);
}

/**
 * ResumeFromPath continues a previous task from a modpack file path (skip unzip).
 * Go service method is ready — run `wails3 generate` (or `wails3 dev`) to refresh this binding's Call.ByID.
 */
export function ResumeFromPath(_filePath: string, _mode: string, _template: string): $CancellablePromise<void> {
    return Promise.reject(new Error("ResumeFromPath binding not generated yet; run wails3 generate")) as $CancellablePromise<void>;
}
