// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DexService is the main service for processing modpacks
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * StartTask starts processing a modpack from file data
 */
export function StartTask(fileData: string, filename: string, mode: string, template: string): $CancellablePromise<void> {
    return $Call.ByID(1446233042, fileData, filename, mode, template);
}

/**
 * StartTaskFromPath starts processing a modpack from a file path
 */
export function StartTaskFromPath(filePath: string, mode: string, template: string): $CancellablePromise<void> {
    return $Call.ByID(3419369309, filePath, mode, template);
}
