// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DialogService provides native file dialogs
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * OpenDirectory opens a native Windows folder picker and returns the selected path.
 */
export function OpenDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3660592233);
}

/**
 * OpenFile opens a native Windows file picker and returns the selected path.
 * extensions is a list of file extensions like ["*.zip", "*.mrpack"]
 */
export function OpenFile(extensions: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(177069516, extensions);
}
