// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadService handles version listing and server installation
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetFabricVersions returns Fabric loader versions
 */
export function GetFabricVersions(mcVersion: string): $CancellablePromise<$models.FabricVersion[] | null> {
    return $Call.ByID(2986853462, mcVersion);
}

/**
 * GetForgePromos returns the Forge promos map (MC version → latest/recommended)
 */
export function GetForgePromos(): $CancellablePromise<{ [_ in string]?: $models.ForgePromo } | null> {
    return $Call.ByID(1791868949);
}

/**
 * GetForgeVersions returns Forge versions for a MC version
 */
export function GetForgeVersions(mcVersion: string): $CancellablePromise<$models.ForgeVersion[] | null> {
    return $Call.ByID(1012175792, mcVersion);
}

/**
 * GetMinecraftVersions returns available Minecraft versions
 */
export function GetMinecraftVersions(): $CancellablePromise<$models.MinecraftVersion[] | null> {
    return $Call.ByID(2162660752);
}

/**
 * GetNeoForgeVersions returns NeoForge versions
 */
export function GetNeoForgeVersions(mcVersion: string): $CancellablePromise<$models.NeoForgeVersion[] | null> {
    return $Call.ByID(4086017086, mcVersion);
}

/**
 * StartServerInstall installs a Minecraft server with the given loader
 */
export function StartServerInstall(loader: string, mcVersion: string, loaderVersion: string): $CancellablePromise<void> {
    return $Call.ByID(3601213272, loader, mcVersion, loaderVersion);
}
