// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GalaxyService handles Galaxy Square operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * SubmitModIDs submits mod IDs to Galaxy Square
 */
export function SubmitModIDs(modType: string, modIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(148186888, modType, modIDs);
}

/**
 * UploadModsFromPaths extracts mod IDs from file paths
 */
export function UploadModsFromPaths(paths: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(2735013154, paths).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
