// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GalaxyService handles Galaxy Square operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * SubmitModIDs submits mod IDs to Galaxy Square
 */
export function SubmitModIDs(modType: string, modIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(148186888, modType, modIDs);
}

/**
 * UploadModsFromPaths extracts mod IDs from file paths
 */
export function UploadModsFromPaths(paths: string[] | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(2735013154, paths);
}
