// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JavaService handles Java operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as java$0 from "../java/models.js";

/**
 * CheckJava checks Java availability
 */
export function CheckJava(path: string): $CancellablePromise<java$0.JavaCheckResult> {
    return $Call.ByID(1763314374, path);
}

/**
 * DetectJavaPaths detects installed Java paths
 */
export function DetectJavaPaths(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1642912875);
}
