// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModCheckService handles mod checking operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * StartModCheck scans JAR files in a folder and classifies them
 */
export function StartModCheck(folderPath: string, bundleName: string): $CancellablePromise<void> {
    return $Call.ByID(474509666, folderPath, bundleName);
}
