// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FabricVersion represents a Fabric version
 */
export class FabricVersion {
    "version": string;
    "stable": boolean;

    /** Creates a new FabricVersion instance. */
    constructor($$source: Partial<FabricVersion> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("stable" in $$source)) {
            this["stable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FabricVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): FabricVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FabricVersion($$parsedSource as Partial<FabricVersion>);
    }
}

/**
 * ForgePromo contains latest/recommended Forge version for a MC version
 */
export class ForgePromo {
    "latest": string;
    "recommended": string;

    /** Creates a new ForgePromo instance. */
    constructor($$source: Partial<ForgePromo> = {}) {
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }
        if (!("recommended" in $$source)) {
            this["recommended"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForgePromo instance from a string or object.
     */
    static createFrom($$source: any = {}): ForgePromo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForgePromo($$parsedSource as Partial<ForgePromo>);
    }
}

/**
 * ForgeVersion represents a Forge version
 */
export class ForgeVersion {
    "version": string;
    "mcversion": string;

    /** Creates a new ForgeVersion instance. */
    constructor($$source: Partial<ForgeVersion> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("mcversion" in $$source)) {
            this["mcversion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForgeVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): ForgeVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForgeVersion($$parsedSource as Partial<ForgeVersion>);
    }
}

/**
 * MinecraftVersion represents a Minecraft version
 */
export class MinecraftVersion {
    "id": string;
    "type": string;

    /** Creates a new MinecraftVersion instance. */
    constructor($$source: Partial<MinecraftVersion> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MinecraftVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): MinecraftVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MinecraftVersion($$parsedSource as Partial<MinecraftVersion>);
    }
}

/**
 * NeoForgeVersion represents a NeoForge version
 */
export class NeoForgeVersion {
    "version": string;
    "latest": boolean;

    /** Creates a new NeoForgeVersion instance. */
    constructor($$source: Partial<NeoForgeVersion> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("latest" in $$source)) {
            this["latest"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NeoForgeVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): NeoForgeVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NeoForgeVersion($$parsedSource as Partial<NeoForgeVersion>);
    }
}
