// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FabricVersion represents a Fabric version
 */
export interface FabricVersion {
    "version": string;
    "stable": boolean;
}

/**
 * ForgePromo contains latest/recommended Forge version for a MC version
 */
export interface ForgePromo {
    "latest": string;
    "recommended": string;
}

/**
 * ForgeVersion represents a Forge version
 */
export interface ForgeVersion {
    "version": string;
    "mcversion": string;
}

/**
 * MinecraftVersion represents a Minecraft version
 */
export interface MinecraftVersion {
    "id": string;
    "type": string;
}

/**
 * NeoForgeVersion represents a NeoForge version
 */
export interface NeoForgeVersion {
    "version": string;
    "latest": boolean;
}
