// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SponsorService handles sponsor operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sponsor$0 from "../sponsor/models.js";

/**
 * List returns all sponsors
 */
export function List(): $CancellablePromise<sponsor$0.Sponsor[]> {
    return $Call.ByID(1117676910).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = sponsor$0.Sponsor.createFrom;
const $$createType1 = $Create.Array($$createType0);
