// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TemplateService handles template operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as template$0 from "../template/models.js";

/**
 * Create creates a new template
 */
export function Create(name: string, version: string, description: string, author: string): $CancellablePromise<template$0.TemplateMetadata | null> {
    return $Call.ByID(190190324, name, version, description, author).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Delete deletes a template
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1774246539, id);
}

/**
 * List returns all templates
 */
export function List(): $CancellablePromise<template$0.TemplateMetadata[]> {
    return $Call.ByID(808957336).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenFolder opens a template folder
 */
export function OpenFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(2095786460, id);
}

/**
 * Update updates a template
 */
export function Update(id: string, metadata: template$0.TemplateMetadata): $CancellablePromise<void> {
    return $Call.ByID(107898193, id, metadata);
}

// Private type creation functions
const $$createType0 = template$0.TemplateMetadata.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
