package modloader

import (
	"archive/zip"
	"fmt"
	"log/slog"
	"io"
	"os"
	"path/filepath"
	"strings"

	"dex/backend/utils"

	"resty.dev/v3"
)

func NewMinecraft(loader, mcv, mlv, path string) XModloader {
	return &Minecraft{
		loader:        loader,
		minecraft:     mcv,
		loaderVersion: mlv,
		path:          path,
		client:        resty.New().SetHeader("User-Agent", "DeEarthX"),
	}
}

type Minecraft struct {
	loader        string
	minecraft     string
	loaderVersion string
	path          string
	client        *resty.Client
}

func (m *Minecraft) Setup() error {
	if err := m.eula(); err != nil {
		return err
	}

	bmclapi := utils.GlobalConfig.GetConfigValue("mirror.bmclapi")
	if bmclapi != true {
		return nil
	}

	switch m.loader {
	case "forge", "neoforge":
		return m.forgeSetup()
	case "fabric", "fabric-loader":
		return m.fabricSetup()
	}

	return nil
}

func (m *Minecraft) Installer() error {
	// Minecraft has no additional installer
	return nil
}

func (m *Minecraft) eula() error {
	context := `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
#Generated by DeEarthX(QQ group:559349662) Tianpao:(https://space.bilibili.com/1728953419)
#DeEarthX (https://bbsmc.net/software/dearthx)
eula=true`
	return os.WriteFile(filepath.Join(m.path, "eula.txt"), []byte(context), 0o644)
}

func (m *Minecraft) forgeSetup() error {
	if utils.VersionCompare(m.minecraft, "1.18") >= 0 {
		// MC >= 1.18: download server jar, extract embedded libraries
		mcpath := filepath.Join(m.path, "libraries", "net", "minecraft", "server", m.minecraft, "server-"+m.minecraft+".jar")
		if err := utils.NewDownloadClient().Download(
			"https://bmclapi2.bangbang93.com/version/"+m.minecraft+"/server",
			mcpath,
		); err != nil {
			return fmt.Errorf("failed to download minecraft server jar: %w", err)
		}

		// Open the server jar as a zip and extract META-INF/libraries/
		r, err := zip.OpenReader(mcpath)
		if err != nil {
			return fmt.Errorf("failed to open server jar: %w", err)
		}
		defer r.Close()

		for _, f := range r.File {
			if strings.HasPrefix(f.Name, "META-INF/libraries/") && !strings.HasSuffix(f.Name, "/") {
				data, err := readZipFile(f)
				if err != nil {
					continue
				}

				relPath := strings.TrimPrefix(f.Name, "META-INF/libraries/")
				destPath := filepath.Join(m.path, "libraries", relPath)
				destDir := filepath.Dir(destPath)

				if err := os.MkdirAll(destDir, 0o755); err != nil {
					return err
				}
				if err := os.WriteFile(destPath, data, 0o644); err != nil {
					return err
				}
			}
		}
	} else {
		// MC < 1.18: download server jar + version JSON + all libraries
		lowv := filepath.Join(m.path, "minecraft_server."+m.minecraft+".jar")

		// Download server jar
		if err := utils.NewDownloadClient().Download(
			"https://bmclapi2.bangbang93.com/version/"+m.minecraft+"/server",
			lowv,
		); err != nil {
			return fmt.Errorf("failed to download minecraft server jar: %w", err)
		}

		// Download version JSON and parse libraries
		resp, err := m.client.R().Get("https://bmclapi2.bangbang93.com/version/" + m.minecraft + "/json")
		if err != nil {
			return fmt.Errorf("failed to fetch version json: %w", err)
		}

		var versionJSON struct {
			Libraries []struct {
				Downloads struct {
					Artifact struct {
						Path string `json:"path"`
					} `json:"artifact"`
				} `json:"downloads"`
			} `json:"libraries"`
		}

		if err := parseJSON(resp.Bytes(), &versionJSON); err != nil {
			return fmt.Errorf("failed to parse version json: %w", err)
		}

		var downloadItems []utils.DownloadOption
		for _, lib := range versionJSON.Libraries {
			if lib.Downloads.Artifact.Path == "" && utils.VersionCompare(m.minecraft, "1.12.2") != 1 {
				continue
			}
			libPath := lib.Downloads.Artifact.Path
			if libPath == "" {
				continue
			}
			downloadItems = append(downloadItems, utils.DownloadOption{
				URL:      "https://bmclapi2.bangbang93.com/maven/" + libPath,
				FilePath:   filepath.Join(m.path, "libraries", libPath),
				UseChunked: false,
			})
		}

		if err := utils.WFastDownload(downloadItems, nil); err != nil {
			if utils.VersionCompare(m.minecraft, "1.12") == 1 {
				// 1.12.x+ errors are real, propagate them
				return err
			}
			// For older versions, log but don't fail
			slog.Warn("library download error", "mcVersion", m.minecraft, "error", err)
		}
	}

	return nil
}

func (m *Minecraft) fabricSetup() error {
	mcpath := filepath.Join(m.path, "server.jar")
	return utils.NewDownloadClient().Download(
		"https://bmclapi2.bangbang93.com/version/"+m.minecraft+"/server",
		mcpath,
	)
}

// readZipFile reads the contents of a file from a zip archive.
func readZipFile(f *zip.File) ([]byte, error) {
	rc, err := f.Open()
	if err != nil {
		return nil, err
	}
	defer rc.Close()
	return io.ReadAll(rc)
}
