// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Sponsor represents a sponsor entry
 */
export class Sponsor {
    "id": number;
    "name": string;
    "imageUrl": string;
    "url": string;

    /**
     * "gold" | "silver" | "bronze"
     */
    "tone": string;

    /** Creates a new Sponsor instance. */
    constructor($$source: Partial<Sponsor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("imageUrl" in $$source)) {
            this["imageUrl"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("tone" in $$source)) {
            this["tone"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Sponsor instance from a string or object.
     */
    static createFrom($$source: any = {}): Sponsor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Sponsor($$parsedSource as Partial<Sponsor>);
    }
}
