// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Sponsor represents a sponsor entry
 */
export interface Sponsor {
    "id": number;
    "name": string;
    "imageUrl": string;
    "url": string;

    /**
     * "gold" | "silver" | "bronze"
     */
    "tone": string;
}
