// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JavaCheckResult represents the result of a Java check
 */
export interface JavaCheckResult {
    "exists": boolean;
    "version"?: JavaVersion | null;
    "error"?: string;
}

/**
 * JavaVersion represents parsed Java version information
 */
export interface JavaVersion {
    "major": number;
    "minor": number;
    "patch": number;
    "fullVersion": string;
    "vendor": string;
    "runtimeVersion"?: string;
}
