// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * JavaCheckResult represents the result of a Java check
 */
export class JavaCheckResult {
    "exists": boolean;
    "version"?: JavaVersion | null;
    "error"?: string;

    /** Creates a new JavaCheckResult instance. */
    constructor($$source: Partial<JavaCheckResult> = {}) {
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JavaCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): JavaCheckResult {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("version" in $$parsedSource) {
            $$parsedSource["version"] = $$createField1_0($$parsedSource["version"]);
        }
        return new JavaCheckResult($$parsedSource as Partial<JavaCheckResult>);
    }
}

/**
 * JavaVersion represents parsed Java version information
 */
export class JavaVersion {
    "major": number;
    "minor": number;
    "patch": number;
    "fullVersion": string;
    "vendor": string;
    "runtimeVersion"?: string;

    /** Creates a new JavaVersion instance. */
    constructor($$source: Partial<JavaVersion> = {}) {
        if (!("major" in $$source)) {
            this["major"] = 0;
        }
        if (!("minor" in $$source)) {
            this["minor"] = 0;
        }
        if (!("patch" in $$source)) {
            this["patch"] = 0;
        }
        if (!("fullVersion" in $$source)) {
            this["fullVersion"] = "";
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JavaVersion instance from a string or object.
     */
    static createFrom($$source: any = {}): JavaVersion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JavaVersion($$parsedSource as Partial<JavaVersion>);
    }
}

// Private type creation functions
const $$createType0 = JavaVersion.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
