// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TemplateMetadata describes a server template
 */
export interface TemplateMetadata {
    "id": string;
    "name": string;
    "version": string;
    "description": string;
    "author": string;
    "created": string;
    "type": string;
}
