// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function ExtractModIDs(paths: string[] | null): $CancellablePromise<string[] | null> {
    return $Call.ByID(365616137, paths);
}

export function SubmitModIDs(modType: string, modIDs: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1672671088, modType, modIDs);
}
