// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModCheckService is the Wails service for the "筛选" (mod check) page.
 * It scans a mods folder, identifies client-side mods, moves them into a
 * .clientmod/<bundleName> folder, and returns per-mod results.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckMods scans folderPath for client-side mods and moves them into
 * <folderPath>/.clientmod/. Returns a result for every scanned jar.
 */
export function CheckMods(folderPath: string): $CancellablePromise<$models.ModCheckResult[] | null> {
    return $Call.ByID(951328736, folderPath);
}
