// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModCheckResult is a single mod's check result returned to the frontend.
 */
export interface ModCheckResult {
    "filename": string;
    "filePath": string;
    "clientSide": string;
    "serverSide": string;
    "source": string;
    "checked": boolean;
    "errors"?: string[] | null;
    "allResults": any[] | null;
}
