// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "changed": { [_ in string]?: any } | null;
            "downloading": { [_ in string]?: any } | null;
            "error": { [_ in string]?: any } | null;
            "file_drop": string[] | null;
            "filter_mods_complete": { [_ in string]?: any } | null;
            "filter_mods_progress": { [_ in string]?: any } | null;
            "filter_mods_start": { [_ in string]?: any } | null;
            "finish": { [_ in string]?: any } | null;
            "info": { [_ in string]?: any } | null;
            "modcheck_complete": { [_ in string]?: any } | null;
            "modcheck_error": { [_ in string]?: any } | null;
            "modcheck_progress": { [_ in string]?: any } | null;
            "modcheck_start": { [_ in string]?: any } | null;
            "server_install_complete": { [_ in string]?: any } | null;
            "server_install_error": { [_ in string]?: any } | null;
            "server_install_progress": { [_ in string]?: any } | null;
            "server_install_start": { [_ in string]?: any } | null;
            "server_install_step": { [_ in string]?: any } | null;
            "unzip": { [_ in string]?: any } | null;
        }
    }
}
