// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as TemplateService from "./templateservice.js";
export {
    TemplateService
};

export type {
    Template,
    TemplateMetadata
} from "./models.js";
