// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Template is a template id paired with its metadata.
 */
export interface Template {
    "id": string;
    "metadata": TemplateMetadata;
}

/**
 * TemplateMetadata describes a server template.
 */
export interface TemplateMetadata {
    "name": string;
    "version": string;
    "description": string;
    "author": string;
    "created": string;
    "type": string;
}
