// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TemplateService is the Wails service for managing server templates.
 * Templates are stored under <appDir>/templates/<id>/ as metadata.json + a data/ folder.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateTemplate creates a new template and returns its id.
 */
export function CreateTemplate(name: string, version: string, description: string, author: string): $CancellablePromise<string> {
    return $Call.ByID(396780917, name, version, description, author);
}

/**
 * DeleteTemplate removes a template and all of its files.
 */
export function DeleteTemplate(id: string): $CancellablePromise<void> {
    return $Call.ByID(2023332534, id);
}

/**
 * GetTemplates lists all templates sorted by creation (newest first).
 */
export function GetTemplates(): $CancellablePromise<$models.Template[] | null> {
    return $Call.ByID(2214646388);
}

/**
 * OpenTemplateFolder reveals the template's data folder in the platform file explorer.
 */
export function OpenTemplateFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(375354337, id);
}

/**
 * UpdateTemplate updates the metadata of an existing template.
 */
export function UpdateTemplate(id: string, name: string, version: string, description: string, author: string): $CancellablePromise<void> {
    return $Call.ByID(1333210096, id, name, version, description, author);
}
