// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function GetConfig(): $CancellablePromise<string> {
    return $Call.ByID(3754947896);
}

export function GetConfigValue(key: string): $CancellablePromise<any> {
    return $Call.ByID(890199209, key);
}

export function LoadConfig(configData: string): $CancellablePromise<void> {
    return $Call.ByID(3548414324, configData);
}

export function UpdateConfig(key: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(3547872105, key, value);
}
