// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DownloadService is a Wails service that provides version list APIs
 * and server install orchestration for the download page.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FetchFabricVersions fetches Fabric loader versions for a given Minecraft version.
 */
export function FetchFabricVersions(mcver: string): $CancellablePromise<$models.FabricVersionEntry[] | null> {
    return $Call.ByID(1364713993, mcver);
}

/**
 * FetchForgePromos fetches Forge latest/recommended promo badges from BMCLAPI.
 */
export function FetchForgePromos(): $CancellablePromise<{ [_ in string]?: $models.ForgePromoEntry } | null> {
    return $Call.ByID(1815404124);
}

/**
 * FetchForgeVersions fetches Forge build versions for a given Minecraft version.
 */
export function FetchForgeVersions(mcver: string): $CancellablePromise<$models.ForgeVersionEntry[] | null> {
    return $Call.ByID(714674541, mcver);
}

/**
 * FetchMcVersions fetches the list of Minecraft versions from BMCLAPI or Mojang.
 */
export function FetchMcVersions(): $CancellablePromise<$models.McVersionResult | null> {
    return $Call.ByID(816499640);
}

/**
 * FetchNeoForgeVersions fetches NeoForge build versions for a given Minecraft version.
 */
export function FetchNeoForgeVersions(mcver: string): $CancellablePromise<$models.NeoForgeVersionEntry[] | null> {
    return $Call.ByID(1246799721, mcver);
}

/**
 * StartInstall begins an async server installation. Returns the install path immediately.
 * Progress is reported via Wails events (server_install_start, server_install_step, etc.).
 */
export function StartInstall(loader: string, mcVersion: string, loaderVersion: string, autoInstall: boolean): $CancellablePromise<string> {
    return $Call.ByID(2328115084, loader, mcVersion, loaderVersion, autoInstall);
}
