// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FabricVersionEntry represents a single Fabric loader version.
 */
export interface FabricVersionEntry {
    "version": string;
    "stable": boolean;
}

/**
 * ForgePromoEntry holds latest/recommended version info for a MC version.
 */
export interface ForgePromoEntry {
    "latest"?: string;
    "recommended"?: string;
}

/**
 * ForgeVersionEntry represents a single Forge build version.
 */
export interface ForgeVersionEntry {
    "version": string;
    "mcversion": string;
    "hash"?: string;
}

/**
 * McVersionEntry represents a single Minecraft version.
 */
export interface McVersionEntry {
    "id": string;
    "type": string;
}

/**
 * McVersionResult is the response for FetchMcVersions.
 */
export interface McVersionResult {
    "versions": McVersionEntry[] | null;
}

/**
 * NeoForgeVersionEntry represents a single NeoForge build version.
 */
export interface NeoForgeVersionEntry {
    "version": string;
    "mcversion": string;
    "installerPath": string;
    "latest": boolean;
}

/**
 * PackCompleteEvent is emitted when modpack processing finishes successfully.
 */
export interface PackCompleteEvent {
    "installPath": string;
    "modpackName": string;

    /**
     * milliseconds
     */
    "duration": number;
}

/**
 * PackDownloadProgressEvent is emitted during mod file downloads.
 */
export interface PackDownloadProgressEvent {
    "total": number;
    "completed": number;
    "fileName": string;
}

/**
 * PackErrorEvent is emitted when modpack processing fails.
 */
export interface PackErrorEvent {
    "error": string;
}

/**
 * PackFilterCompleteEvent is emitted when mod filtering finishes.
 */
export interface PackFilterCompleteEvent {
    "filteredCount": number;
    "movedCount": number;
}

/**
 * PackFilterProgressEvent is emitted during mod filtering.
 */
export interface PackFilterProgressEvent {
    "current": number;
    "total": number;
    "modName": string;
}

/**
 * PackFilterStartEvent is emitted when mod filtering begins.
 */
export interface PackFilterStartEvent {
    "totalMods": number;
}

/**
 * PackProgressEvent is emitted to report progress within the current step.
 */
export interface PackProgressEvent {
    "step": string;
    "progress": number;
}

/**
 * PackStartEvent is emitted when a modpack processing begins.
 */
export interface PackStartEvent {
    "modpackName": string;
    "minecraftVersion": string;
    "loaderType": string;
    "loaderVersion": string;

    /**
     * "server" or "client"
     */
    "mode": string;
}

/**
 * PackStepEvent is emitted when the processing advances to a new major step.
 */
export interface PackStepEvent {
    "step": string;
    "stepIndex": number;
    "totalSteps": number;
}

/**
 * ServerInstallCompleteEvent is emitted when the install finishes successfully.
 */
export interface ServerInstallCompleteEvent {
    "installPath": string;

    /**
     * milliseconds
     */
    "duration": number;
}

/**
 * ServerInstallErrorEvent is emitted when the install fails.
 */
export interface ServerInstallErrorEvent {
    "error": string;
}

/**
 * ServerInstallProgressEvent is emitted to report progress within a step.
 */
export interface ServerInstallProgressEvent {
    "step": string;
    "progress": number;
}

/**
 * ServerInstallStartEvent is emitted when a server install begins.
 */
export interface ServerInstallStartEvent {
    "modpackName": string;
    "minecraftVersion": string;
    "loaderType": string;
    "loaderVersion": string;
}

/**
 * ServerInstallStepEvent is emitted when the install progresses to a new step.
 */
export interface ServerInstallStepEvent {
    "step": string;
    "stepIndex": number;
    "totalSteps": number;
}
