// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModpackService is the Wails service that orchestrates the full
 * modpack processing pipeline (extract → parse → download mods →
 * filter client-side mods → install modloader → optional zip/reveal).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * ProcessModpack runs the full pipeline on an in-memory modpack buffer.
 * Returns the instance install path immediately; progress is reported via Wails events.
 */
export function ProcessModpack(buffer: string | null, filename: string, mode: string): $CancellablePromise<string> {
    return $Call.ByID(3632742208, buffer, filename, mode);
}

/**
 * ProcessModpackFromPath reads a modpack file from disk and runs the full pipeline.
 * Returns the instance install path immediately; progress is reported via Wails events.
 */
export function ProcessModpackFromPath(path: string, mode: string): $CancellablePromise<string> {
    return $Call.ByID(3190158775, path, mode);
}
